"""The gateway, unmodified, against real providers over the real internet.

--------------------------------------------------------------------------
What this proves that `tests/contract/` cannot
--------------------------------------------------------------------------

The contract tier runs a real uvicorn against a real socket, and it is the
best rig in this repo. It still cannot tell you any of the following, because
every one of them is a property of the thing on the other end of the socket:

* that `ModelSpec.api_model` is a string a provider will accept
* that a 2 s connect budget survives DNS + TCP + a TLS handshake to Virginia
* that a 20 s first-event budget survives a real model's think time
* what a provider's error body actually looks like, and therefore whether
  `errors.from_http_status` classifies it the way the taxonomy assumes
* which SSE frames exist. `fakes/wire.py` emits the frames we thought of.

So this module builds the SAME app -- `server.app.build_app` -- with
`fake_upstreams=False` and a policy naming real catalog models, runs it on a
real socket, and points a real client at it. Nothing here is a special code
path: if it were, it would prove nothing about the one that ships.

--------------------------------------------------------------------------
Spend
--------------------------------------------------------------------------

Every generation request is `max_tokens=16` with a one-sentence prompt. A
full run is single-digit tokens of output per provider and the total is
printed in USD at the bottom, computed from the SAME `catalog.price_of` the
gateway bills with -- not from a second table that would drift from it.

    python -m live.smoke              # everything
    python -m live.smoke --no-spend   # only the free parts (routing, 400s)
"""

from __future__ import annotations

import argparse
import json
import os
import socket
import sys
import tempfile
import threading
import time
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import Any

import httpx
import uvicorn
from starlette.applications import Starlette

from live import env
from llmgw.catalog import (
    DEFAULT_CATALOG,
    Catalog,
    ModelSpec,
    price_of,
)
from llmgw.clocks import Budgets
from llmgw.server.app import build_app
from llmgw.server.config import ServerConfig
from llmgw.sse import SSEParser
from llmgw.surfaces import (
    ANTHROPIC_MESSAGES,
    OPENAI_CHAT,
    OPENAI_RESPONSES,
    Surface,
    Usage,
)

PROMPT = "Reply with exactly the word: ok"
MAX_TOKENS = 16
"""Sixteen, and a prompt that asks for one word. The point of a live smoke is
the transport, the framing and the accounting -- none of which get more true
with a longer answer, and all of which get more expensive."""

GHOST_MODEL_ID = "live.ghost-deepseek"
GHOST_API_MODEL = "deepseek-v4-ghost-does-not-exist"
"""A candidate that fails NATURALLY.

`tests/contract/test_fallback.py` makes its candidate fail by telling a fake
to fail -- which proves the executor's control flow and assumes the shape of
the failure. This one is a wire model id that DeepSeek has never heard of, so
the failure is generated by DeepSeek, in DeepSeek's own words, with DeepSeek's
own status code. That difference is the entire point of Task 3: the taxonomy
has only ever been shown bodies we wrote ourselves.
"""


# ==========================================================================
# The catalog and policy this run uses
# ==========================================================================


IDENTITY_PROVIDER = "anthropic-identity"
IDENTITY_MODEL_ID = "anthropic.haiku-4-5-identity"
"""The same Anthropic model, reached through a provider that asks for an
uncompressed body. See `live_catalog` -- this pair is a bug reproduction, not
a feature."""

OPENAI_MODEL_ID = "openai.gpt-4o-mini"
OPENAI_STRICT_MODEL_ID = "openai.gpt-5-nano"
"""Both shipped catalog rows now (`gpt-4o-mini` since 16 Sep 2026, finding
36; `gpt-5-nano` since Phase F). Until then this module carried its own
copies with an alias-less `openai.gpt-4o-mini`, and because `with_overrides`
REPLACES a row, the override silently dropped the `gpt-4o-mini-2024-07-18`
alias the shipped row declares -- which is the id OpenAI echoes and the one
`echo_roundtrip` and the Responses two-turn case send back. The live run
must see the catalog the gateway ships, aliases included."""

DEEPSEEK_MODEL_ID = "deepseek.deepseek-v4-flash"


def live_catalog(base: Catalog = DEFAULT_CATALOG) -> Catalog:
    """The shipped catalog, plus what a live run needs that it does not have.

    Two additions, each of which is a finding rather than a convenience:

    1. `live.ghost-deepseek` -- a candidate that fails NATURALLY. The wire
       model id is not one DeepSeek serves, so the 400 is DeepSeek's, in
       DeepSeek's words.
    2. `anthropic-identity` -- the shipped `anthropic` provider plus
       `accept-encoding: identity`. `Upstream` builds its `httpx.AsyncClient`
       with no header overrides, so httpx advertises `gzip, deflate, br,
       zstd`; Anthropic honours it and gzips the SSE body; `aiter_raw()`
       forwards the compressed bytes undecoded; and `content-encoding` is not
       in `FORWARDED_RESPONSE_HEADERS`, so the client receives gzip octets
       labelled `text/event-stream`. `ProviderConn.extra_headers` is merged
       LAST by `build_headers`, which makes it the only lever that exists
       today. The real fix belongs in `Upstream._client_for`.

    The `openai` provider and its two models used to be a third and fourth
    addition; they ship in the catalog now and are deliberately NOT overridden
    (see `OPENAI_MODEL_ID`).
    """
    ghost = ModelSpec(
        id=GHOST_MODEL_ID, provider="deepseek", api_model=GHOST_API_MODEL,
        input_per_m=0.14, output_per_m=0.28, priced_at="2026-09-09",
    )
    identity_provider = replace(
        base.providers["anthropic"], id=IDENTITY_PROVIDER,
        extra_headers={"accept-encoding": "identity"},
        credential_id="anthropic",
    )
    identity_model = replace(
        base.models["anthropic.haiku-4-5"], id=IDENTITY_MODEL_ID,
        provider=IDENTITY_PROVIDER,
        # A derived row must not inherit the source row's declared aliases:
        # one alias claimed by two catalog ids is a construction error (A1).
        aliases=(),
    )
    return base.with_overrides(
        providers={IDENTITY_PROVIDER: identity_provider},
        models={m.id: m for m in (ghost, identity_model)},
    )


POLICY_TOML = f"""
default_workload = "deepseek"

[defaults.budgets]
total = 90.0
connect = 5.0
first_event = 30.0
progress = 20.0
client_stall = 30.0

[defaults.retry]
max_attempts = 1
base_delay = 0.25
max_delay = 2.0
respect_retry_after = true

# The shipped catalog, unmodified. Expected to TRUNCATE -- see live_catalog.
[workloads.anthropic]
incumbent = "anthropic.haiku-4-5"

# The same model, one request header different.
[workloads.anthropic-identity]
incumbent = "{IDENTITY_MODEL_ID}"

[workloads.deepseek]
incumbent = "deepseek.deepseek-v4-flash"

[workloads.openai]
incumbent = "{OPENAI_MODEL_ID}"

[workloads.openrouter]
incumbent = "openrouter.mistral-small-2603"

# Task 3. Candidate on ONE real provider, incumbent on a DIFFERENT real
# provider, and the candidate fails because the model id is not real -- not
# because a fixture told it to.
[workloads.fallback]
incumbent = "{OPENAI_MODEL_ID}"
candidate = "{GHOST_MODEL_ID}"

# The same shape, failing for the OTHER real reason: a candidate that exists
# but whose schema rejects the body. InvalidRequest is the row people are
# surprised by; this is that row, generated by OpenAI rather than asserted
# by us.
[workloads.fallback-schema]
incumbent = "deepseek.deepseek-v4-flash"
candidate = "{OPENAI_STRICT_MODEL_ID}"
"""

WORKLOAD_SURFACE: dict[str, Surface] = {
    "anthropic": ANTHROPIC_MESSAGES,
    "anthropic-identity": ANTHROPIC_MESSAGES,
    "deepseek": OPENAI_CHAT,
    "openai": OPENAI_CHAT,
    "openrouter": OPENAI_CHAT,
    "fallback": OPENAI_CHAT,
    "fallback-schema": OPENAI_CHAT,
}
"""Which client dialect each workload is addressed in.

Not cosmetic, and it is the first thing a live run teaches you about the
routing model: `PassthroughEndpoint` binds ONE surface per route and forwards
to `Surface.path`, so every target inside a plan must speak the dialect of the
route the client used. A fallback from an `anthropic`-kind provider to an
`openai`-kind one is not expressible -- it would POST an Anthropic Messages
body to `/v1/chat/completions`. That is why both fallback workloads pair two
OpenAI-shaped providers, and it is a real constraint on how a two-target plan
can be written.
"""

ROUTE_FOR: dict[str, str] = {
    "anthropic_messages": "/anthropic/v1/messages",
    "openai_chat": "/v1/chat/completions",
}


def body_for(surface: Surface, *, stream: bool) -> dict[str, Any]:
    body: dict[str, Any] = {
        # Overwritten on the wire by `upstream.apply_api_model`; sent because
        # both dialects require the field and because a body that omits it is
        # a body we would be testing a different code path with.
        "model": "placeholder",
        "max_tokens": MAX_TOKENS,
        "messages": [{"role": "user", "content": PROMPT}],
        "stream": stream,
    }
    if stream and surface is OPENAI_CHAT:
        # Without this, an OpenAI-dialect stream carries NO usage frame and
        # every streamed request is billed by estimate. Anthropic always
        # reports; OpenAI-shaped providers only report when asked.
        body["stream_options"] = {"include_usage": True}
    return body


# ==========================================================================
# Running the gateway on a real socket
# ==========================================================================


@dataclass
class GatewayServer:
    app: Starlette
    server: uvicorn.Server
    thread: threading.Thread
    port: int

    @property
    def base_url(self) -> str:
        return f"http://127.0.0.1:{self.port}"

    def stop(self, timeout: float = 10.0) -> None:
        self.server.should_exit = True
        self.thread.join(timeout)
        if self.thread.is_alive():  # pragma: no cover
            self.server.force_exit = True
            self.thread.join(timeout)


def serve(app: Starlette, *, startup_timeout: float = 15.0) -> GatewayServer:
    """uvicorn on its own thread with `lifespan="on"`.

    `lifespan="on"` is not optional: the upstream pool is created in the
    Starlette lifespan so that it can be CLOSED at shutdown, and a server
    started without it answers every request with a 500.
    """
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.bind(("127.0.0.1", 0))
    sock.listen(64)
    port = sock.getsockname()[1]
    server = uvicorn.Server(
        uvicorn.Config(app, log_level="error", access_log=False, lifespan="on")
    )
    thread = threading.Thread(target=server.run, kwargs={"sockets": [sock]},
                              daemon=True, name=f"llmgw-live-{port}")
    thread.start()
    deadline = time.monotonic() + startup_timeout
    while not server.started:
        if not thread.is_alive() or time.monotonic() > deadline:  # pragma: no cover
            raise RuntimeError("gateway failed to start")
        time.sleep(0.005)
    return GatewayServer(app=app, server=server, thread=thread, port=port)


def build_live_app(policy_path: str, **overrides: Any) -> Starlette:
    """`build_app` with real providers. The ONE line that matters is
    `fake_upstreams=False`, and it is the default -- see `ServerConfig`."""
    settings: dict[str, Any] = {
        "catalog": live_catalog(),
        "fake_upstreams": False,
        "policy_file": policy_path,
        "budgets": Budgets(total=90.0, connect=5.0, first_event=30.0,
                           progress=20.0, client_stall=30.0),
    }
    settings.update(overrides)
    return build_app(ServerConfig(**settings).validated())


# ==========================================================================
# One measured request
# ==========================================================================


@dataclass
class Measured:
    """Everything one live request taught us. Never carries a credential."""

    label: str
    workload: str
    model_id: str
    stream: bool
    status: int = 0
    ttft_ms: float | None = None
    """Time to the FIRST BYTE of the response body, not to the headers.

    The two are far apart on a real provider and identical on the fakes, which
    is exactly why `first_event` is its own budget: the status line arrives in
    milliseconds and the first token arrives when the model starts talking.
    """
    headers_ms: float | None = None
    total_ms: float = 0.0
    usage: Usage = field(default_factory=Usage)
    usd: float = 0.0
    gw: dict[str, str] = field(default_factory=dict)
    upstream_headers: dict[str, str] = field(default_factory=dict)
    events: list[str] = field(default_factory=list)
    """Every distinct SSE `event:` name (or synthetic tag) the stream carried.
    The list the fakes never produced is the finding."""
    error_body: str = ""
    note: str = ""

    @property
    def gw_line(self) -> str:
        keys = ("x-gw-attempts", "x-gw-served-by", "x-gw-workload-id",
                "x-gw-body-modified")
        return " ".join(f"{k.removeprefix('x-gw-')}={self.gw[k]}"
                        for k in keys if k in self.gw)


def usd_of(usage: Usage, model: ModelSpec) -> float:
    """Measured cost, from the catalog the gateway itself prices with.

    Cache reads are priced through `price_of(cached=True)`, which falls back to
    the full input rate when a model does not support caching -- the fallback
    that must not be zero, or every uncached provider looks free.
    """
    write_rate = (model.cache_write_per_m if model.cache_write_per_m is not None
                  else model.input_per_m)
    return (
        usage.input_tokens * model.input_per_m
        + usage.cache_read_tokens * price_of(model, cached=True)
        + usage.cache_write_tokens * write_rate
        + usage.output_tokens * model.output_per_m
    ) / 1_000_000


def measure(
    gw: GatewayServer, workload: str, *, stream: bool, catalog: Catalog,
    model_id: str, label: str | None = None, timeout: float = 90.0,
) -> Measured:
    """Send one request through the gateway and account for it honestly."""
    surface = WORKLOAD_SURFACE[workload]
    route = f"/workloads/{workload}{ROUTE_FOR[surface.name]}"
    body = body_for(surface, stream=stream)
    out = Measured(label=label or f"{workload}/{'stream' if stream else 'json'}",
                   workload=workload, model_id=model_id, stream=stream)
    model = catalog.models[model_id]
    started = time.perf_counter()
    with httpx.Client(timeout=httpx.Timeout(timeout, connect=10.0)) as client:
        if not stream:
            resp = client.post(gw.base_url + route, json=body)
            out.headers_ms = out.ttft_ms = (time.perf_counter() - started) * 1000
            out.total_ms = out.ttft_ms
            out.status = resp.status_code
            out.gw = {k: v for k, v in resp.headers.items() if k.startswith("x-gw-")}
            out.upstream_headers = _interesting(resp.headers)
            if resp.status_code == 200:
                _usage_from_json(resp.content, out.usage)
            else:
                out.error_body = resp.text[:400]
            out.usd = usd_of(out.usage, model)
            return out

        parser = SSEParser(max_frame_bytes=1 << 20)
        seen: list[str] = []
        with client.stream("POST", gw.base_url + route, json=body) as resp:
            out.headers_ms = (time.perf_counter() - started) * 1000
            out.status = resp.status_code
            out.gw = {k: v for k, v in resp.headers.items() if k.startswith("x-gw-")}
            out.upstream_headers = _interesting(resp.headers)
            if resp.status_code != 200:
                out.error_body = resp.read().decode("utf-8", "replace")[:400]
                out.total_ms = (time.perf_counter() - started) * 1000
                return out
            body_bytes = 0
            try:
                for chunk in resp.iter_raw():
                    if out.ttft_ms is None and chunk:
                        out.ttft_ms = (time.perf_counter() - started) * 1000
                    body_bytes += len(chunk)
                    if body_bytes == len(chunk) and chunk[:2] == b"\x1f\x8b":
                        out.note = ("first two body bytes are 1f 8b -- this is a "
                                    "GZIP MEMBER, not SSE text")
                    for ev in parser.feed(chunk):
                        _note_event(ev, seen)
                        surface.apply_usage(ev, out.usage)
                for ev in parser.close():
                    _note_event(ev, seen)
                    surface.apply_usage(ev, out.usage)
            except httpx.RemoteProtocolError as exc:
                # C2 in the wild: a post-commitment failure ends the body with
                # no chunked terminator, and the client's own HTTP stack -- not
                # ours -- raises. Recorded rather than re-raised, because the
                # truncation IS the observation.
                out.note = (out.note + " | " if out.note else "") + (
                    f"TRUNCATED after {body_bytes} B: {type(exc).__name__}: {exc}"
                )
        out.total_ms = (time.perf_counter() - started) * 1000
    out.events = seen
    out.usd = usd_of(out.usage, model)
    return out


def _note_event(ev: Any, seen: list[str]) -> None:
    if ev.is_comment:
        tag = "<sse-comment>"
    elif ev.event:
        tag = ev.event
    elif ev.data.strip() == b"[DONE]":
        tag = "[DONE]"
    else:
        tag = "<unnamed-data>"
    if tag not in seen:
        seen.append(tag)


def _usage_from_json(body: bytes, usage: Usage) -> None:
    """Non-streaming usage. Read here rather than by a surface on purpose:
    `Surface.apply_usage` takes an SSE frame, and the buffered path has none."""
    try:
        parsed = json.loads(body)
    except ValueError:
        usage.parse_failures += 1
        return
    u = parsed.get("usage") or {}
    if "input_tokens" in u:  # Anthropic: disjoint already
        usage.input_tokens = int(u.get("input_tokens") or 0)
        usage.cache_read_tokens = int(u.get("cache_read_input_tokens") or 0)
        usage.cache_write_tokens = int(u.get("cache_creation_input_tokens") or 0)
    else:  # OpenAI: prompt_tokens INCLUDES cached_tokens, so subtract
        cached = int(((u.get("prompt_tokens_details") or {}).get("cached_tokens")) or 0)
        usage.input_tokens = max(0, int(u.get("prompt_tokens") or 0) - cached)
        usage.cache_read_tokens = cached
    usage.output_tokens = int(u.get("output_tokens") or u.get("completion_tokens") or 0)
    usage.input_exact = usage.output_exact = True


INTERESTING_PREFIXES = (
    "anthropic-", "x-request-id", "request-id", "openai-", "x-ratelimit",
    "retry-after", "x-openrouter", "cf-ray", "server", "x-envoy",
)


def _interesting(headers: httpx.Headers) -> dict[str, str]:
    """Response headers the fakes never sent. Forwarded ones only -- the
    gateway's allowlist decides what a client can see, and what survives it
    is itself a finding."""
    return {
        k: v for k, v in headers.items()
        if any(k.startswith(p) for p in INTERESTING_PREFIXES)
    }


# ==========================================================================
# One-status-line proof, over a raw socket
# ==========================================================================


def raw_request(gw: GatewayServer, route: str, body: dict[str, Any],
                *, timeout: float = 90.0) -> bytes:
    """Speak HTTP/1.1 by hand and return every byte the client received.

    `httpx` parses the response and hands back one object, which cannot
    distinguish "one status line" from "one status line that a second one
    replaced". Counting `HTTP/1.1 ` occurrences in the raw octets is the only
    honest form of the C1 assertion, and a fallback is exactly the case where
    a broken gateway would emit two.
    """
    payload = json.dumps(body).encode()
    request = (
        f"POST {route} HTTP/1.1\r\nHost: 127.0.0.1:{gw.port}\r\n"
        f"Content-Type: application/json\r\nContent-Length: {len(payload)}\r\n"
        f"Accept: text/event-stream\r\nConnection: close\r\n\r\n"
    ).encode() + payload
    sock = socket.create_connection(("127.0.0.1", gw.port), timeout=timeout)
    sock.settimeout(timeout)
    try:
        sock.sendall(request)
        buf = bytearray()
        while True:
            chunk = sock.recv(65536)
            if not chunk:
                break
            buf += chunk
        return bytes(buf)
    finally:
        sock.close()


def status_lines(raw: bytes) -> list[str]:
    return [
        line.decode("latin-1")
        for line in raw.split(b"\r\n")
        if line.startswith(b"HTTP/1.")
    ]


# ==========================================================================
# The run
# ==========================================================================


MODEL_OF = {
    "anthropic": "anthropic.haiku-4-5",
    "anthropic-identity": IDENTITY_MODEL_ID,
    "deepseek": "deepseek.deepseek-v4-flash",
    "openai": OPENAI_MODEL_ID,
    "openrouter": "openrouter.mistral-small-2603",
    "fallback": OPENAI_MODEL_ID,
    "fallback-schema": "deepseek.deepseek-v4-flash",
}

STREAM_WORKLOADS = ("anthropic", "anthropic-identity", "deepseek", "openai",
                    "openrouter")
FALLBACK_WORKLOADS = ("fallback", "fallback-schema")



def _missing_key_for(model_id: str, catalog: Catalog) -> str | None:
    """The env var this model's provider needs and does not have, or None.

    Reads the requirement off the catalog row rather than a list here, so a
    provider added to the catalog cannot be silently exercised without its
    key -- or silently skipped once it has one.
    """
    try:
        target = catalog.resolve(model_id)
    except Exception:  # noqa: BLE001 - an unroutable id is the caller's problem
        return None
    name = getattr(target.provider, "api_key_env", None)
    if not name:
        return None
    return None if os.environ.get(name) else name


def echo_roundtrip(gw: GatewayServer, *, out=sys.stdout) -> None:
    """The two-turn loop against a real provider (PLAN-2 A1, finding 42).

    Turn one names the catalog id. OpenAI answers with the snapshot id it
    served (`gpt-4o-mini-2024-07-18` on 16 Sep 2026). Turn two sends that id
    back exactly as an SDK's conversation object would. Before aliases the
    second call was `400 policy_error: unknown model`; now it must route to the
    same target. Two buffered calls, a few tokens each.
    """
    route = f"/workloads/openai{ROUTE_FOR['openai_chat']}"
    body = body_for(OPENAI_CHAT, stream=False)
    body["model"] = OPENAI_MODEL_ID
    first = httpx.post(f"{gw.base_url}{route}", json=body, timeout=60)
    echoed = first.json().get("model") if first.status_code == 200 else None
    print(f"  echo-roundtrip turn 1: {first.status_code} model={echoed!r}", file=out)
    if not echoed:
        print("  echo-roundtrip: FAIL (turn 1 did not return a model)", file=out)
        return
    body["model"] = echoed
    second = httpx.post(f"{gw.base_url}{ROUTE_FOR['openai_chat']}", json=body, timeout=60)
    served = second.headers.get("x-gw-served-by")
    verdict = "PASS" if second.status_code == 200 else "FAIL"
    print(f"  echo-roundtrip turn 2 (model={echoed!r}): {second.status_code} "
          f"served_by={served} -> {verdict}", file=out)
    if second.status_code != 200:
        print(f"    {second.text[:300]}", file=out)


def usage_fields_case(gw: GatewayServer, *, out=sys.stdout) -> None:
    """PLAN-2 B3 (a): a buffered gpt-4o-mini call; the record's new kinds
    exist and reasoning is zero on a non-reasoning model."""
    route = f"/workloads/openai{ROUTE_FOR['openai_chat']}"
    body = body_for(OPENAI_CHAT, stream=False)
    body["model"] = OPENAI_MODEL_ID
    resp = httpx.post(f"{gw.base_url}{route}", json=body, timeout=60)
    ok = resp.status_code == 200
    usage = resp.json().get("usage", {}) if ok else {}
    details = usage.get("completion_tokens_details") or {}
    reasoning = details.get("reasoning_tokens", 0) or 0
    verdict = "PASS" if ok and reasoning == 0 else "FAIL"
    print(f"  usage-fields: {resp.status_code} prompt={usage.get('prompt_tokens')} "
          f"completion={usage.get('completion_tokens')} reasoning={reasoning} -> {verdict}",
          file=out)
    print("    (record-side: AccountingRecord.reasoning_tokens / audio_* / "
          "server_tool_calls exist; see tests/unit/test_units.py)", file=out)


_CACHEABLE_SYSTEM = (
    "You are a meticulous assistant for a software team. " * 60
    + "Answer with one word."
)
"""About 1,100 tokens: over Haiku 4.5's 4,096-token cache minimum? No -- and
that is the finding this case is written to make visible. Anthropic's minimum
cacheable prompt is 4,096 tokens on Haiku 4.5 and 1,024 on Sonnet 4.6, so a
1,100-token system prompt caches on Sonnet and silently does not on Haiku
(capabilities/anthropic.md §7). The case reports what happened rather than
asserting a read, and says which side of the threshold it was on."""


def cache_write_read_case(gw: GatewayServer, *, out=sys.stdout) -> None:
    """PLAN-2 B3 (b): the same cached system prompt twice on Haiku 4.5.

    Reports cache_creation on the first call and cache_read on the second,
    and prices the read at `cached_input_per_m`. Spends two short calls."""
    route = f"/workloads/anthropic{ROUTE_FOR['anthropic_messages']}"
    body = {
        "model": "anthropic.haiku-4-5",
        "max_tokens": 8,
        "system": [{"type": "text", "text": _CACHEABLE_SYSTEM,
                    "cache_control": {"type": "ephemeral"}}],
        "messages": [{"role": "user", "content": "ping"}],
    }
    spec = DEFAULT_CATALOG.models["anthropic.haiku-4-5"]
    seen = []
    for turn in (1, 2):
        resp = httpx.post(f"{gw.base_url}{route}", json=body, timeout=60)
        u = resp.json().get("usage", {}) if resp.status_code == 200 else {}
        seen.append((resp.status_code, u))
        print(f"  cache turn {turn}: {resp.status_code} input={u.get('input_tokens')} "
              f"cache_write={u.get('cache_creation_input_tokens')} "
              f"cache_read={u.get('cache_read_input_tokens')}", file=out)
    read = (seen[1][1] or {}).get("cache_read_input_tokens") or 0
    write = (seen[0][1] or {}).get("cache_creation_input_tokens") or 0
    if read:
        usd = read * spec.cached_input_per_m / 1e6
        print(f"  cache: second call read {read} tokens, priced at cached rate "
              f"{spec.cached_input_per_m}/M = ${usd:.7f} -> PASS", file=out)
    elif write == 0:
        print("  cache: no write on turn 1 -- prompt under Haiku 4.5's 4,096-token "
              "cache minimum (documented; use Sonnet 4.6 for a 1,024 minimum) -> INFO",
              file=out)
    else:
        print("  cache: written but not read on turn 2 -> FAIL", file=out)


def big_vision_case(gw: GatewayServer, *, out=sys.stdout) -> None:
    """PLAN-2 B4 (c): a ~10 MiB base64 image body. Skipped unless
    LLMGW_SMOKE_BIG_VISION=1, because it needs the per-surface body cap
    (agent S's change) and costs real vision tokens."""
    if os.environ.get("LLMGW_SMOKE_BIG_VISION") != "1":
        print("  big-vision: SKIPPED (set LLMGW_SMOKE_BIG_VISION=1 to send the "
              "10 MiB body; it costs one vision call)", file=out)
        return
    import base64
    # A valid-looking JPEG header followed by filler: the provider will
    # reject the image, which is fine -- the assertion is that the GATEWAY
    # did not 413 it first.
    payload = base64.b64encode(b"\xff\xd8\xff" + b"\x00" * (10 * 1024 * 1024)).decode()
    route = f"/workloads/openai{ROUTE_FOR['openai_chat']}"
    body = {
        "model": OPENAI_MODEL_ID, "max_tokens": 8,
        "messages": [{"role": "user", "content": [
            {"type": "text", "text": "Describe this."},
            {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{payload}",
                                                "detail": "low"}},
        ]}],
    }
    resp = httpx.post(f"{gw.base_url}{route}", json=body, timeout=120)
    verdict = "PASS" if resp.status_code != 413 else "FAIL (gateway 413)"
    print(f"  big-vision: {resp.status_code} served_by={resp.headers.get('x-gw-served-by')} "
          f"-> {verdict}", file=out)



# ==========================================================================
# PLAN-2 Phase C5: the shapes the sweeps found untested, plus the new routes.
# Every case prints one PASS/FAIL/INFO line and spends a few thousandths of a
# cent; none is load-bearing for the measured tables above.
# ==========================================================================

_SONNET_ID = "anthropic.sonnet-4-6"


def _case(out, label: str, resp: httpx.Response, ok: bool, detail: str = "") -> None:
    verdict = "PASS" if ok else "FAIL"
    served = resp.headers.get("x-gw-served-by", "-")
    print(f"  {label}: {resp.status_code} served_by={served} {detail} -> {verdict}", file=out)


def anthropic_tool_roundtrip_case(gw: GatewayServer, *, out=sys.stdout) -> None:
    """Tool call, then the tool result replayed -- never exercised on the
    Anthropic surface before (capabilities/anthropic.md gap 10)."""
    route = f"/workloads/anthropic{ROUTE_FOR['anthropic_messages']}"
    tool = {"name": "get_weather", "description": "Weather for a city",
            "input_schema": {"type": "object", "properties": {"city": {"type": "string"}},
                             "required": ["city"]}}
    body = {"model": "anthropic.haiku-4-5", "max_tokens": 128, "tools": [tool],
            "tool_choice": {"type": "tool", "name": "get_weather"},
            "messages": [{"role": "user", "content": "Weather in Pune?"}]}
    first = httpx.post(f"{gw.base_url}{route}", json=body, timeout=60)
    ok = first.status_code == 200
    tool_use = None
    if ok:
        tool_use = next((b for b in first.json().get("content", [])
                         if b.get("type") == "tool_use"), None)
        ok = tool_use is not None
    _case(out, "anthropic-tools turn 1", first, ok,
          f"stop={first.json().get('stop_reason') if first.status_code == 200 else ''}")
    if not ok:
        return
    body2 = {"model": "anthropic.haiku-4-5", "max_tokens": 64, "tools": [tool], "messages": [
        {"role": "user", "content": "Weather in Pune?"},
        {"role": "assistant", "content": first.json()["content"]},
        {"role": "user", "content": [{"type": "tool_result", "tool_use_id": tool_use["id"],
                                      "content": "31C, clear"}]},
    ]}
    second = httpx.post(f"{gw.base_url}{route}", json=body2, timeout=60)
    _case(out, "anthropic-tools turn 2", second, second.status_code == 200)


def anthropic_vision_and_pdf_case(gw: GatewayServer, *, out=sys.stdout) -> None:
    """Base64 and URL images, and a one-page PDF, on the Anthropic surface."""
    import base64

    route = f"/workloads/anthropic{ROUTE_FOR['anthropic_messages']}"
    # A 1x1 PNG; the point is the request shape, not the vision.
    # A valid 1x1 RGBA PNG (the previous hex had a malformed IDAT and Anthropic
    # rejected it with a 400 that looked like a gateway fault, 18 Sep 2026).
    png = ("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA"
           "60e6kgAAAABJRU5ErkJggg==")
    for label, source in (
        ("anthropic-vision base64",
         {"type": "base64", "media_type": "image/png", "data": png}),
        ("anthropic-vision url", {"type": "url",
                                  "url": "https://upload.wikimedia.org/wikipedia/commons/"
                                         "4/47/PNG_transparency_demonstration_1.png"}),
    ):
        body = {"model": "anthropic.haiku-4-5", "max_tokens": 32, "messages": [
            {"role": "user", "content": [
                {"type": "image", "source": source},
                {"type": "text", "text": "One word: what is this?"}]}]}
        r = httpx.post(f"{gw.base_url}{route}", json=body, timeout=60)
        if label.endswith("url") and r.status_code == 400 and "url" in r.text.lower():
            # Anthropic could not fetch the URL (hotlink policy, transient);
            # the request shape still transited the gateway. Report, don't fail.
            _case(out, label, r, True,
                  detail="400 = provider could not fetch the URL; shape transited")
            continue
        _case(out, label, r, r.status_code == 200,
              detail="" if r.status_code == 200 else r.text[:200])
    pdf = base64.b64encode(
        b"%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n"
        b"2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n"
        b"3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 200 200]>>endobj\n"
        b"trailer<</Root 1 0 R>>\n%%EOF"
    ).decode()
    body = {"model": "anthropic.haiku-4-5", "max_tokens": 32, "messages": [
        {"role": "user", "content": [
            {"type": "document", "source": {"type": "base64", "media_type": "application/pdf",
                                            "data": pdf}},
            {"type": "text", "text": "How many pages?"}]}]}
    r = httpx.post(f"{gw.base_url}{route}", json=body, timeout=60)
    _case(out, "anthropic-pdf", r, r.status_code in (200, 400),
          "(400 = provider rejected the toy PDF; the request shape transited)")


def anthropic_structured_and_adaptive_case(gw: GatewayServer, *, out=sys.stdout) -> None:
    """`output_config.format` (structured outputs) and adaptive thinking on
    Sonnet 4.6, which is where both are supported. The bare route, because a
    workload-prefixed request runs the workload's incumbent (Haiku) whatever
    the body says; only the bare route lets the body's model pin Sonnet."""
    route = ROUTE_FOR["anthropic_messages"]
    body = {"model": _SONNET_ID, "max_tokens": 64,
            "output_config": {"format": {"type": "json_schema", "schema": {
                "type": "object", "properties": {"answer": {"type": "string"}},
                "required": ["answer"], "additionalProperties": False}}},
            "messages": [{"role": "user", "content": "Reply with the word pong as `answer`."}]}
    r = httpx.post(f"{gw.base_url}{route}", json=body, timeout=60)
    ok = r.status_code == 200
    if ok:
        text = "".join(b.get("text", "") for b in r.json().get("content", []))
        try:
            ok = "answer" in json.loads(text)
        except ValueError:
            ok = False
    _case(out, "anthropic-structured (sonnet-4-6)", r, ok or r.status_code == 400,
          "(400 = the account lacks structured outputs; shape transited)")
    body = {"model": _SONNET_ID, "max_tokens": 2048, "thinking": {"type": "adaptive"},
            "messages": [{"role": "user", "content": "Is 91 prime? One word."}]}
    r = httpx.post(f"{gw.base_url}{route}", json=body, timeout=90)
    kinds = ({b.get("type") for b in r.json().get("content", [])}
             if r.status_code == 200 else set())
    _case(out, "anthropic-adaptive-thinking (sonnet-4-6)", r, r.status_code == 200,
          f"blocks={sorted(kinds)}")


def openai_parallel_tools_case(gw: GatewayServer, *, out=sys.stdout) -> None:
    route = f"/workloads/openai{ROUTE_FOR['openai_chat']}"
    tool = {"type": "function", "function": {
        "name": "get_weather", "description": "Weather for a city",
        "parameters": {"type": "object", "properties": {"city": {"type": "string"}},
                       "required": ["city"]}}}
    body = {"model": OPENAI_MODEL_ID, "max_tokens": 128, "tools": [tool],
            "parallel_tool_calls": True, "tool_choice": "required",
            "messages": [{"role": "user", "content": "Weather in Pune and in Oslo, both."}]}
    r = httpx.post(f"{gw.base_url}{route}", json=body, timeout=60)
    calls = []
    if r.status_code == 200:
        calls = r.json()["choices"][0]["message"].get("tool_calls") or []
    _case(out, "openai-parallel-tools", r, r.status_code == 200 and len(calls) >= 1,
          f"tool_calls={len(calls)}")


def phase_c_routes_case(gw: GatewayServer, *, out=sys.stdout) -> None:
    """`/v1/models` (no upstream call), `/v1/embeddings`, `count_tokens`."""
    r = httpx.get(f"{gw.base_url}/v1/models", timeout=30)
    ids = {m["id"] for m in r.json().get("data", [])} if r.status_code == 200 else set()
    _case(out, "models (openai list)", r, r.status_code == 200 and OPENAI_MODEL_ID in ids,
          f"n={len(ids)}")
    r = httpx.get(f"{gw.base_url}/anthropic/v1/models", timeout=30)
    ids = {m["id"] for m in r.json().get("data", [])} if r.status_code == 200 else set()
    _case(out, "models (anthropic list)", r,
          r.status_code == 200 and "anthropic.haiku-4-5" in ids, f"n={len(ids)}")
    r = httpx.post(f"{gw.base_url}/v1/embeddings", timeout=60,
                   json={"model": "openai.text-embedding-3-small", "input": "pong"})
    usage = r.json().get("usage", {}) if r.status_code == 200 else {}
    _case(out, "embeddings", r, r.status_code == 200 and usage.get("prompt_tokens", 0) > 0,
          f"prompt_tokens={usage.get('prompt_tokens')}")
    r = httpx.post(f"{gw.base_url}/anthropic/v1/messages/count_tokens",
                   json={"model": "anthropic.haiku-4-5",
                         "messages": [{"role": "user", "content": "count these tokens"}]},
                   timeout=60)
    n = r.json().get("input_tokens") if r.status_code == 200 else None
    _case(out, "count_tokens", r, r.status_code == 200 and isinstance(n, int),
          f"input_tokens={n}")


# ==========================================================================
# PLAN-2 Phase F: `/v1/responses` (CONTRACTS.md C22). Every shape below was
# first seen on the wire in `capabilities/captures-responses.md` (17 Sep
# 2026); these cases assert that the same shapes survive the gateway. All on
# the bare route, so the body's `model` picks the target through the alias
# table -- which is exactly what the Responses SDK does when it echoes ids.
# ==========================================================================

RESPONSES_ROUTE = "/v1/responses"
RESPONSES_TERMINALS = ("response.completed", "response.incomplete")


@dataclass
class ResponsesStream:
    """One streamed `/v1/responses` call: the measurement, the response
    headers, and every frame in order as `(event name, parsed payload)`.
    `payload` is None for comments, `[DONE]` and unparseable data."""

    measured: Measured
    headers: dict[str, str] = field(default_factory=dict)
    frames: list[tuple[str, dict[str, Any] | None]] = field(default_factory=list)
    body_text: str = ""

    @property
    def names(self) -> list[str]:
        return [name for name, _ in self.frames]

    @property
    def terminal(self) -> tuple[str, dict[str, Any] | None]:
        """The last non-comment frame; `("", None)` for an empty stream."""
        for name, payload in reversed(self.frames):
            if name != "<sse-comment>":
                return name, payload
        return "", None

    @property
    def response(self) -> dict[str, Any]:
        """The full `response` object off the terminal frame, or `{}`."""
        _, payload = self.terminal
        resp = (payload or {}).get("response")
        return resp if isinstance(resp, dict) else {}


def _responses_body(model: str, text: str, *, stream: bool,
                    max_output_tokens: int = MAX_TOKENS, **extra: Any) -> dict[str, Any]:
    """`max_output_tokens` is this dialect's cap and 16 is OpenAI's floor
    (probe 9: 8 is a 400 `integer_below_min_value`)."""
    body: dict[str, Any] = {"model": model, "input": text, "stream": stream,
                            "max_output_tokens": max_output_tokens}
    body.update(extra)
    return body


def _responses_stream(gw: GatewayServer, body: dict[str, Any], *, label: str,
                      model_id: str, catalog: Catalog,
                      timeout: float = 90.0) -> ResponsesStream:
    """POST one streamed body and account for it the way `measure` does:
    first byte, total, and usage folded by the SAME `OPENAI_RESPONSES.apply_usage`
    the gateway bills with, so a row in the results table is comparable with
    the chat rows above it."""
    measured = Measured(label=label, workload="responses", model_id=model_id, stream=True)
    result = ResponsesStream(measured=measured)
    parser = SSEParser(max_frame_bytes=1 << 20)
    seen: list[str] = []
    started = time.perf_counter()
    with httpx.Client(timeout=httpx.Timeout(timeout, connect=10.0)) as client:
        with client.stream("POST", gw.base_url + RESPONSES_ROUTE, json=body) as resp:
            measured.headers_ms = (time.perf_counter() - started) * 1000
            measured.status = resp.status_code
            measured.gw = {k: v for k, v in resp.headers.items() if k.startswith("x-gw-")}
            measured.upstream_headers = _interesting(resp.headers)
            result.headers = dict(resp.headers)
            if resp.status_code != 200:
                result.body_text = resp.read().decode("utf-8", "replace")[:400]
                measured.error_body = result.body_text
                measured.total_ms = (time.perf_counter() - started) * 1000
                return result
            try:
                for chunk in resp.iter_raw():
                    if measured.ttft_ms is None and chunk:
                        measured.ttft_ms = (time.perf_counter() - started) * 1000
                    for ev in parser.feed(chunk):
                        _collect_responses_frame(ev, result, seen)
                for ev in parser.close():
                    _collect_responses_frame(ev, result, seen)
            except httpx.RemoteProtocolError as exc:
                measured.note = f"TRUNCATED: {type(exc).__name__}: {exc}"
        measured.total_ms = (time.perf_counter() - started) * 1000
    measured.events = seen
    measured.usd = usd_of(measured.usage, catalog.models[model_id])
    return result


def _collect_responses_frame(ev: Any, result: ResponsesStream, seen: list[str]) -> None:
    _note_event(ev, seen)
    OPENAI_RESPONSES.apply_usage(ev, result.measured.usage)
    if ev.is_comment:
        result.frames.append(("<sse-comment>", None))
        return
    if ev.data.strip() == b"[DONE]":
        result.frames.append(("[DONE]", None))
        return
    try:
        payload = json.loads(ev.data)
    except ValueError:
        payload = None
    if not isinstance(payload, dict):
        payload = None
    name = ev.event or (payload or {}).get("type") or "<unnamed-data>"
    result.frames.append((str(name), payload))


def _verdict(out, label: str, status: int, headers: dict[str, str] | httpx.Headers,
             ok: bool, detail: str = "") -> None:
    """`_case` for a call that has no `httpx.Response` (a consumed stream)."""
    verdict = "PASS" if ok else "FAIL"
    served = headers.get("x-gw-served-by", "-")
    print(f"  {label}: {status} served_by={served} {detail} -> {verdict}", file=out)


def responses_openai_case(gw: GatewayServer, *, catalog: Catalog,
                          out=sys.stdout) -> list[Measured]:
    """Cases 1-5: happy paths streamed and buffered, the cap-hit ending, the
    two-turn state loop through the alias table, and the background refusal.
    Returns the streamed happy path as a measured row."""
    rows: list[Measured] = []

    # 1. Streamed happy path -- the measured row.
    s = _responses_stream(gw, _responses_body(OPENAI_MODEL_ID, PROMPT, stream=True),
                          label="responses/openai/stream", model_id=OPENAI_MODEL_ID,
                          catalog=catalog)
    rows.append(s.measured)
    first = s.names[0] if s.names else ""
    terminal, _ = s.terminal
    ctype = s.headers.get("content-type", "")
    ok = (s.measured.status == 200 and ctype.startswith("text/event-stream")
          and first == "response.created" and terminal == "response.completed"
          and "[DONE]" not in s.names
          and "x-gw-served-by" in s.headers and "x-gw-model" in s.headers)
    _verdict(out, "responses stream", s.measured.status, s.headers, ok,
             f"first={first} last={terminal} frames={len(s.frames)} "
             f"done_marker={'[DONE]' in s.names} model_hdr={s.headers.get('x-gw-model')} "
             f"ctype={ctype.split(';')[0]}")

    # 2. Buffered happy path: A1 rewrite puts the CATALOG id in `model`.
    r = httpx.post(f"{gw.base_url}{RESPONSES_ROUTE}", timeout=60,
                   json=_responses_body(OPENAI_MODEL_ID, PROMPT, stream=False))
    j = r.json() if r.status_code == 200 else {}
    u = j.get("usage") or {}
    total_ok = (isinstance(u.get("total_tokens"), int)
                and u.get("total_tokens")
                == (u.get("input_tokens", -1) + u.get("output_tokens", -1)))
    _case(out, "responses buffered", r,
          r.status_code == 200 and j.get("status") == "completed"
          and j.get("model") == OPENAI_MODEL_ID
          and r.headers.get("x-gw-body-modified") == "1" and total_ok,
          f"status={j.get('status')} model={j.get('model')!r} "
          f"body_modified={r.headers.get('x-gw-body-modified')} "
          f"usage={u.get('input_tokens')}+{u.get('output_tokens')}={u.get('total_tokens')}")

    # 3. Cap hit: the terminal frame is `response.incomplete`, never followed
    # by (or replaced with) a `response.completed` (C22).
    s = _responses_stream(
        gw, _responses_body(OPENAI_MODEL_ID, "Write a 300-word essay about rivers.",
                            stream=True, max_output_tokens=16),
        label="responses/openai/incomplete", model_id=OPENAI_MODEL_ID, catalog=catalog)
    terminal, _ = s.terminal
    reason = (s.response.get("incomplete_details") or {}).get("reason")
    _verdict(out, "responses incomplete", s.measured.status, s.headers,
             s.measured.status == 200 and terminal == "response.incomplete"
             and reason == "max_output_tokens" and "response.completed" not in s.names,
             f"last={terminal} reason={reason} stop={s.measured.usage.stop_reason} "
             f"out={s.measured.usage.output_tokens}")

    # 4. Two turns of provider-held state. Turn B names the SNAPSHOT id
    # OpenAI echoes (the gateway rewrote A's `model` to the catalog id, so an
    # SDK that had talked to OpenAI directly is what this simulates); the
    # alias table must route it to the same row (A1).
    a = httpx.post(f"{gw.base_url}{RESPONSES_ROUTE}", timeout=60,
                   json=_responses_body(OPENAI_MODEL_ID,
                                        "My favourite colour is teal. Reply OK.",
                                        stream=False))
    a_id = a.json().get("id") if a.status_code == 200 else None
    _case(out, "responses two-turn A", a, bool(a_id), f"id={a_id}")
    if a_id:
        b = httpx.post(f"{gw.base_url}{RESPONSES_ROUTE}", timeout=60,
                       json=_responses_body("gpt-4o-mini-2024-07-18",
                                            "What is my favourite colour? One word.",
                                            stream=False, previous_response_id=a_id))
        bj = b.json() if b.status_code == 200 else {}
        _case(out, "responses two-turn B (snapshot id + previous_response_id)", b,
              b.status_code == 200 and bj.get("previous_response_id") == a_id,
              f"previous_response_id_echo={bj.get('previous_response_id') == a_id} "
              f"model={bj.get('model')!r}"
              + ("" if b.status_code == 200 else f" {b.text[:200]}"))

    # 5. `background: true` is refused before any target is chosen.
    r = httpx.post(f"{gw.base_url}{RESPONSES_ROUTE}", timeout=60,
                   json=_responses_body(OPENAI_MODEL_ID, "hi", stream=False, background=True))
    _case(out, "responses background refused", r,
          r.status_code == 400 and "background" in r.text.lower() and _no_upstream(r),
          f"names_background={'background' in r.text.lower()} "
          f"no_upstream={_no_upstream(r)}")
    return rows


def _no_upstream(resp: httpx.Response) -> bool:
    """True when the gateway answered without opening a socket upstream.

    The gateway does not OMIT `x-gw-served-by` on such a response; it sends
    the literal `-` (the same sentinel `_case` prints) with `x-gw-attempts: 0`.
    Asserting on header absence would fail every gateway-side 400 for the
    wrong reason, so this is the form the assertion takes."""
    served = resp.headers.get("x-gw-served-by")
    return served in (None, "-") and resp.headers.get("x-gw-attempts", "0") == "0"


def _metric_value(gw: GatewayServer, family: str, *needles: str) -> float | None:
    """The sample value of the first `/metrics` line in `family` whose label
    set contains every needle, or None when there is no such line yet."""
    text = httpx.get(f"{gw.base_url}/metrics", timeout=10).text
    for line in text.splitlines():
        if line.startswith(family) and all(n in line for n in needles):
            try:
                return float(line.rsplit(" ", 1)[1])
            except (IndexError, ValueError):
                return None
    return None


def responses_web_search_case(gw: GatewayServer, *, catalog: Catalog, out=sys.stdout) -> None:
    """Case 6: one hosted `web_search_preview` call (about USD 0.03: the
    search is per-call priced, not per token). Asserts the lifecycle event
    reached the client, that the provider's own count is on the terminal
    frame, and that the gateway counted it as a server tool call."""
    before = _metric_value(gw, "llmgw_server_tool_calls_total", "web_search_requests") or 0.0
    s = _responses_stream(
        gw, _responses_body(OPENAI_MODEL_ID, "What is today's top headline? One sentence.",
                            stream=True, max_output_tokens=64,
                            tools=[{"type": "web_search_preview"}]),
        label="responses/openai/web-search", model_id=OPENAI_MODEL_ID, catalog=catalog,
        timeout=120)
    terminal, _ = s.terminal
    n = ((s.response.get("tool_usage") or {}).get("web_search") or {}).get("num_requests")
    counted = dict(s.measured.usage.server_tool_calls).get("web_search_requests")
    _verdict(out, "responses web-search", s.measured.status, s.headers,
             s.measured.status == 200 and "response.web_search_call.completed" in s.names
             and isinstance(n, int) and n >= 1 and terminal in RESPONSES_TERMINALS,
             f"last={terminal} web_search_call.completed="
             f"{'response.web_search_call.completed' in s.names} num_requests={n} "
             f"client_side_count={counted} "
             f"tokens={s.measured.usage.input_tokens}+{s.measured.usage.output_tokens}")
    # The gateway's own accounting runs as the stream closes; give it a moment.
    after = None
    for _ in range(20):
        after = _metric_value(gw, "llmgw_server_tool_calls_total", "web_search_requests")
        if after is not None and after > before:
            break
        time.sleep(0.1)
    delta = None if after is None else after - before
    verdict = "PASS" if delta is not None and delta >= 1 else "FAIL"
    print(f"  responses web-search metric: llmgw_server_tool_calls_total"
          f"{{web_search_requests}} +{delta} -> {verdict}", file=out)


def responses_reasoning_case(gw: GatewayServer, *, catalog: Catalog, out=sys.stdout) -> None:
    """Case 7: a reasoning model on the surface. `reasoning_tokens` is a
    subset of `output_tokens` and may be 0 at effort low (probe 4); the
    assertion is that the field arrives as an integer, not its value."""
    if OPENAI_STRICT_MODEL_ID not in catalog.models:
        print(f"  responses reasoning: SKIPPED ({OPENAI_STRICT_MODEL_ID} is not in the "
              "catalog; its price row is still unconfirmed) -> INFO", file=out)
        return
    s = _responses_stream(
        gw, _responses_body(OPENAI_STRICT_MODEL_ID,
                            "What is 17*23? Answer with the number only.",
                            stream=True, max_output_tokens=256, reasoning={"effort": "low"}),
        label="responses/openai/gpt-5-nano", model_id=OPENAI_STRICT_MODEL_ID, catalog=catalog)
    terminal, _ = s.terminal
    reasoning = ((s.response.get("usage") or {}).get("output_tokens_details") or {}
                 ).get("reasoning_tokens")
    text = "".join(
        part.get("text", "") for item in s.response.get("output", [])
        if item.get("type") == "message" for part in item.get("content", []))
    _verdict(out, "responses reasoning (gpt-5-nano)", s.measured.status, s.headers,
             s.measured.status == 200 and terminal == "response.completed"
             and isinstance(reasoning, int) and not isinstance(reasoning, bool),
             f"last={terminal} reasoning_tokens={reasoning!r} "
             f"out={s.measured.usage.output_tokens} text={text!r} "
             f"model={s.response.get('model')!r}")


def responses_deepseek_case(gw: GatewayServer, *, catalog: Catalog, out=sys.stdout) -> None:
    """Case 8: DeepSeek's stateless door on the same surface. A small cap is
    routinely spent on reasoning alone (probe 10a), so `incomplete` is as
    good as `completed`; what must hold is 200 + a usage object, the
    gateway's own 400 for provider-held state (C22), and reasoning streamed
    in clear."""
    r = httpx.post(f"{gw.base_url}{RESPONSES_ROUTE}", timeout=90,
                   json=_responses_body(DEEPSEEK_MODEL_ID, "Say hi.", stream=False,
                                        max_output_tokens=128))
    j = r.json() if r.status_code == 200 else {}
    u = j.get("usage") if isinstance(j.get("usage"), dict) else {}
    reasoning = (u.get("output_tokens_details") or {}).get("reasoning_tokens")
    _case(out, "responses deepseek buffered", r,
          r.status_code == 200 and j.get("status") in ("completed", "incomplete")
          and isinstance(j.get("usage"), dict),
          f"status={j.get('status')} model={j.get('model')!r} "
          f"usage={u.get('total_tokens')} reasoning={reasoning}")
    r = httpx.post(f"{gw.base_url}{RESPONSES_ROUTE}", timeout=90,
                   json=_responses_body(DEEPSEEK_MODEL_ID, "Say hi.", stream=False,
                                        max_output_tokens=128, previous_response_id="resp_x"))
    _case(out, "responses deepseek previous_response_id refused (C22)", r,
          r.status_code == 400 and _no_upstream(r),
          f"no_upstream={_no_upstream(r)} {r.text[:120]!r}")
    s = _responses_stream(
        gw, _responses_body(DEEPSEEK_MODEL_ID, "What is 17*23? Answer with the number only.",
                            stream=True, max_output_tokens=128),
        label="responses/deepseek/stream", model_id=DEEPSEEK_MODEL_ID, catalog=catalog)
    terminal, _ = s.terminal
    _verdict(out, "responses deepseek stream", s.measured.status, s.headers,
             s.measured.status == 200 and terminal in RESPONSES_TERMINALS
             and "response.reasoning_text.delta" in s.names,
             f"last={terminal} reasoning_text.delta="
             f"{'response.reasoning_text.delta' in s.names} "
             f"reasoning_tokens={s.measured.usage.reasoning_tokens} "
             f"out={s.measured.usage.output_tokens}")


def responses_case(gw: GatewayServer, *, catalog: Catalog, out=sys.stdout) -> list[Measured]:
    """Phase F, all of it. Returns the rows for the results table."""
    rows = responses_openai_case(gw, catalog=catalog, out=out)
    responses_web_search_case(gw, catalog=catalog, out=out)
    responses_reasoning_case(gw, catalog=catalog, out=out)
    responses_deepseek_case(gw, catalog=catalog, out=out)
    return rows


def run(*, spend: bool = True, out=sys.stdout) -> list[Measured]:
    catalog = live_catalog()
    results: list[Measured] = []
    with tempfile.TemporaryDirectory(prefix="llmgw-live-") as tmp:
        policy = Path(tmp) / "live.toml"
        policy.write_text(POLICY_TOML, encoding="utf-8")
        gw = serve(build_live_app(str(policy)))
        try:
            print(f"gateway on {gw.base_url}  fake_upstreams=False", file=out)
            for wl in FALLBACK_WORKLOADS:
                probe = httpx.get(f"{gw.base_url}/workloads/{wl}/probe",
                                  timeout=10).json()
                print(f"  probe /workloads/{wl}: "
                      f"targets={[t['served_by'] for t in probe['targets']]} "
                      f"upstream_called={probe['upstream_called']}", file=out)

            if not spend:
                return results

            for wl in STREAM_WORKLOADS:
                missing = _missing_key_for(MODEL_OF[wl], catalog)
                if missing is not None:
                    print(f"  {wl}/stream: SKIP (no {missing})", file=out)
                    continue
                results.append(measure(gw, wl, stream=True, catalog=catalog,
                                       model_id=MODEL_OF[wl]))
            for wl in ("anthropic", "anthropic-identity"):
                results.append(measure(
                    gw, wl, stream=False, catalog=catalog, model_id=MODEL_OF[wl],
                    label=f"{wl}/non-streaming"))

            echo_roundtrip(gw, out=out)
            usage_fields_case(gw, out=out)
            cache_write_read_case(gw, out=out)
            big_vision_case(gw, out=out)
            # Phase C5: the shapes the sweeps found untested, and the new routes.
            anthropic_tool_roundtrip_case(gw, out=out)
            anthropic_vision_and_pdf_case(gw, out=out)
            anthropic_structured_and_adaptive_case(gw, out=out)
            openai_parallel_tools_case(gw, out=out)
            phase_c_routes_case(gw, out=out)
            # Phase F: the Responses surface (C22). One measured row.
            results.extend(responses_case(gw, catalog=catalog, out=out))

            # ---- Task 3: fallback across two real providers, raw socket ----
            for wl in FALLBACK_WORKLOADS:
                surface = WORKLOAD_SURFACE[wl]
                route = f"/workloads/{wl}{ROUTE_FOR[surface.name]}"
                started = time.perf_counter()
                raw = raw_request(gw, route, body_for(surface, stream=True))
                elapsed = (time.perf_counter() - started) * 1000
                results.append(_measure_from_raw(raw, catalog, elapsed, wl))
        finally:
            gw.stop()
    render(results, out=out)
    return results


def _measure_from_raw(raw: bytes, catalog: Catalog, elapsed_ms: float,
                      workload: str = "fallback") -> Measured:
    lines = status_lines(raw)
    head, _, body = raw.partition(b"\r\n\r\n")
    headers = {}
    for line in head.split(b"\r\n")[1:]:
        name, _, value = line.partition(b":")
        headers[name.decode("latin-1").lower().strip()] = value.decode("latin-1").strip()
    out = Measured(label=f"{workload}/raw-socket", workload=workload,
                   model_id=MODEL_OF[workload], stream=True)
    out.status = int(lines[0].split()[1]) if lines else 0
    out.total_ms = elapsed_ms
    out.gw = {k: v for k, v in headers.items() if k.startswith("x-gw-")}
    out.upstream_headers = {k: v for k, v in headers.items()
                            if any(k.startswith(p) for p in INTERESTING_PREFIXES)}
    out.note = f"status lines on the wire: {len(lines)} ({', '.join(lines)})"
    parser = SSEParser(max_frame_bytes=1 << 20)
    seen: list[str] = []
    payload = _dechunk(body) if headers.get("transfer-encoding") == "chunked" else body
    for ev in parser.feed(payload) + parser.close():
        _note_event(ev, seen)
        OPENAI_CHAT.apply_usage(ev, out.usage)
    out.events = seen
    out.usd = usd_of(out.usage, catalog.models[out.model_id])
    return out


def _dechunk(body: bytes) -> bytes:
    """HTTP/1.1 chunked decoding, because we asked for the raw octets.

    Reading a streamed body without this is how you end up asserting against
    hex chunk sizes interleaved with SSE frames and concluding the framing is
    broken.
    """
    out = bytearray()
    rest = body
    while True:
        line, sep, rest = rest.partition(b"\r\n")
        if not sep:
            break
        try:
            size = int(line.split(b";")[0] or b"0", 16)
        except ValueError:
            break
        if size == 0:
            break
        out += rest[:size]
        rest = rest[size + 2:]
    return bytes(out)


def render(results: list[Measured], out=sys.stdout) -> None:
    print("", file=out)
    print("=" * 78, file=out)
    print("LIVE SMOKE -- real providers, real TLS, real latency", file=out)
    print("=" * 78, file=out)
    total = 0.0
    for r in results:
        total += r.usd
        print(f"\n{r.label}  [{r.model_id}]", file=out)
        print(f"  HTTP {r.status}   headers {_ms(r.headers_ms)}   "
              f"first byte {_ms(r.ttft_ms)}   total {_ms(r.total_ms)}", file=out)
        u = r.usage
        print(f"  tokens in={u.input_tokens} out={u.output_tokens} "
              f"cache_read={u.cache_read_tokens} cache_write={u.cache_write_tokens} "
              f"exact={u.exact} (in={u.input_exact} out={u.output_exact})", file=out)
        print(f"  USD {r.usd:.8f}", file=out)
        if r.gw:
            print(f"  X-Gw: {r.gw_line}", file=out)
            print(f"        policy={r.gw.get('x-gw-policy-id', '-')} "
                  f"catalog={r.gw.get('x-gw-catalog-id', '-')}", file=out)
        if r.events:
            print(f"  SSE events: {', '.join(r.events)}", file=out)
        if r.upstream_headers:
            print(f"  forwarded upstream headers: "
                  f"{json.dumps(r.upstream_headers)[:300]}", file=out)
        if r.note:
            print(f"  {r.note}", file=out)
        if r.error_body:
            print(f"  error body: {r.error_body}", file=out)
    print("", file=out)
    print(f"TOTAL MEASURED SPEND: ${total:.8f} over {len(results)} requests", file=out)


def _ms(value: float | None) -> str:
    return "-" if value is None else f"{value:8.1f} ms"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="live end-to-end smoke")
    parser.add_argument("--no-spend", action="store_true",
                        help="routing and probe only; sends no generation request")
    args = parser.parse_args(argv)
    for status in env.ensure_loaded():
        print(f"  {status}", file=sys.stderr)
    # Only what every run needs. A provider whose key is absent is SKIPPED
    # per workload below rather than refusing the whole run: the point of
    # this harness is to exercise the providers you actually have, and
    # demanding a key for one you do not have makes it exercise none of them.
    env.require("ANTHROPIC_API_KEY", "DEEPSEEK_API_KEY")
    run(spend=not args.no_spend)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
